### ISSUE TITLE
Project 1 links reversed

### ISSUE THREAD

**Issue by DBBrowne** [alaraayan/portfolio#1]
https://github.com/alaraayan/portfolio/blob/ad8ee1c8ed9d494fd960de775c48d1c01df24d31/src/components/Projects.js#L61-L62

Someone shared your portfolio page.  Looks great!

But, I think the links for github are reversed for your pacman project.

**Comment by alaraayan** [comment]
<img src="https://media.giphy.com/media/KJ1f5iTl4Oo7u/giphy-downsized-large.gif" />
